import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { Avatar, Project, Scene } from '$lib/types';
import { base64ToBlob } from '$lib/helpers/image';
import { formatDuration } from '$lib/helpers/duration';

function slugify(text: string): string {
	return (
		text
			.toLowerCase()
			.replace(/\[[^\]]+\]/g, '')
			.replace(/[^a-z0-9\s-]/g, '')
			.trim()
			.split(/\s+/)
			.slice(0, 4)
			.join('-')
			.replace(/-+/g, '-') || 'scene'
	);
}

function pad(n: number, width: number): string {
	return n.toString().padStart(width, '0');
}

function sceneFilenameStem(scene: Scene, index: number, totalDigits: number): string {
	const slug = slugify(scene.audioLine);
	return `${pad(index + 1, totalDigits)}_${scene.type}_${slug}`;
}

function brollMarkdown(scene: Scene, index: number): string {
	return [
		`# Scene ${index + 1} — B-roll`,
		'',
		`**Audio line**`,
		'',
		`> ${scene.audioLine}`,
		'',
		`**Estimated duration:** ${scene.durationSeconds}s`,
		'',
		'---',
		'',
		'## Shot description',
		'',
		scene.shotDescription ?? '_No description provided._',
		'',
		'## Recording instructions',
		'',
		scene.recordingInstructions ?? '_No instructions provided._',
		''
	].join('\n');
}

function readme(project: Project, avatar: Avatar | undefined): string {
	const totalSeconds = project.scenes.reduce((s, sc) => s + sc.durationSeconds, 0);
	const lines: string[] = [
		`# ${project.name}`,
		'',
		`Generated by Showrunner on ${new Date(project.updatedAt).toLocaleString()}.`,
		'',
		`**Avatar:** ${avatar?.name ?? 'unknown'}`,
		`**Total scenes:** ${project.scenes.length}`,
		`**Estimated runtime:** ${formatDuration(totalSeconds)}`,
		'',
		'**Source script:** `script.txt` (full original script as entered in Showrunner)',
		'',
		'## Storyboard',
		''
	];

	project.scenes.forEach((scene, i) => {
		const num = pad(i + 1, 2);
		lines.push(`### ${num} · ${scene.type === 'avatar' ? 'Avatar' : 'B-roll'} (${scene.durationSeconds}s)`);
		lines.push('');
		lines.push(`> ${scene.audioLine}`);
		lines.push('');
		if (scene.type === 'avatar') {
			if (scene.framing) lines.push(`**Framing:** ${scene.framing}`);
			if (scene.actionDescription) {
				lines.push('');
				lines.push(`**Action:** ${scene.actionDescription}`);
			}
		} else {
			if (scene.shotDescription) {
				lines.push(`**Shot:** ${scene.shotDescription}`);
				lines.push('');
			}
			if (scene.recordingInstructions) {
				lines.push(`**Record:** ${scene.recordingInstructions}`);
			}
		}
		lines.push('');
	});

	lines.push('## File map');
	lines.push('');
	const totalDigits = String(project.scenes.length).length;
	project.scenes.forEach((scene, i) => {
		const stem = sceneFilenameStem(scene, i, totalDigits);
		const lipsync = scene.lipsyncVideoBase64 ? `\`${stem}.mp4\`` : '';
		const voiceover = scene.voiceoverBase64 ? `\`${stem}.mp3\`` : '';
		const broll = scene.type === 'broll' ? `\`${stem}.md\`` : '';
		const files = [lipsync, voiceover, broll].filter(Boolean).join(' · ');
		lines.push(`- Scene ${i + 1}: ${files || '_no outputs_'}`);
	});
	lines.push('');

	return lines.join('\n');
}

export async function exportProjectBundle(
	project: Project,
	avatar: Avatar | undefined
): Promise<void> {
	const zip = new JSZip();
	const totalDigits = String(project.scenes.length).length || 2;

	for (let i = 0; i < project.scenes.length; i++) {
		const scene = project.scenes[i];
		const stem = sceneFilenameStem(scene, i, totalDigits);

		if (scene.voiceoverBase64) {
			zip.file(`${stem}.mp3`, base64ToBlob(scene.voiceoverBase64));
		}

		if (scene.type === 'avatar' && scene.lipsyncVideoBase64) {
			zip.file(`${stem}.mp4`, base64ToBlob(scene.lipsyncVideoBase64));
		} else if (scene.type === 'avatar' && scene.avatarImageBase64) {
			// fallback: include the image if lipsync didn't render
			zip.file(`${stem}.png`, base64ToBlob(scene.avatarImageBase64));
		}

		if (scene.type === 'broll') {
			zip.file(`${stem}.md`, brollMarkdown(scene, i));
		}
	}

	zip.file('script.txt', project.script ?? '');
	zip.file('README.md', readme(project, avatar));

	const blob = await zip.generateAsync({ type: 'blob' });
	const safeName = project.name.replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase() || 'showrunner-project';
	saveAs(blob, `${safeName}.zip`);
}
